### ISSUE TITLE
2nd and subsequent consumers do not work correctly

### ISSUE THREAD

**Issue by mutability** [flightaware/kafkatcl#2]
```
$ tclsh
% package require kafka
1.1
% ::kafka::setup_consumer -brokers hekri
% set c1 [::kafka::topic_consumer #auto adept.commands]
::kafka_topic0
% $c1 info partitions
1
% set c2 [::kafka::topic_consumer #auto adept.mlat.results]
::kafka_topic1
% $c2 info partitions
kafka error: topic 'adept.mlat.results' not found
% ::kafka::consumer info partitions adept.commands
1
% ::kafka::consumer info partitions adept.mlat.results
kafka error: topic 'adept.mlat.results' not found
```

However adept.mlat.results absolutely does exist, and in fact if you don't create the first consumer it works fine:

```
$ tclsh
% package require kafka
1.1
% ::kafka::setup_consumer -brokers hekri
% set c2 [::kafka::topic_consumer #auto adept.mlat.results]
::kafka_topic0
% $c2 info partitions
512
```

It seems to be mostly a metadata issue when creating consumers; a workaround seems to be to do an "info partitions" for any topic before creating the first consumers:

```
$ tclsh
% package require kafka
1.1
% ::kafka::setup_consumer -brokers hekri
% ::kafka::consumer info partitions adept.commands
1
% set c1 [::kafka::topic_consumer #auto adept.commands]
::kafka_topic0
% $c1 info partitions
1
% set c2 [::kafka::topic_consumer #auto adept.mlat.results]
::kafka_topic1
% $c2 info partitions
512
```

**Comment by mutability** [comment]
A simpler workaround seems to be to force a metadata refresh by ::kafka::consumer meta refresh (but see issue #3) before creating anything.

**Comment by lehenbauer** [comment]
I've fixed the meta refresh/print suboptions problem referenced by Issue #3.  Can you see how that has affected this issue?  Thanks.

**Comment by mutability** [comment]
I rebuilt with a1549353926213957b34b20a7049026f115f41e9 and the first set of commands above still fails in the same way.

**Comment by lehenbauer** [comment]
Commit 73cd5df4fc94eb864adf644062269357b72825cc solves this problem.

**Comment by mutability** [comment]
Looks good, thanks!
